apiVersion: v1
kind: Secret
metadata:
  name: football-secret
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:<>@5.75.228.74:10000/postgres?sslmode=disable"
  ADMIN_PASSWORD: "changeme"
  PORT: "8080"
